import turtle
t=turtle.Turtle() #거북이 모양 생성
t.shape("arrow") #모양을 거북이로
#right->rt forward->fd left->lt
t.color("blue")
t.penup()
t.goto(-200,0)
t.pendown()
t.width(5)
t.circle(50)
t.penup()
t.color("black")
t.goto(-70,0)
t.pendown()
t.circle(50)
t.penup()
t.color("red")
t.goto(60,0)
t.pendown()
t.circle(50)
t.penup()
t.color("yellow")
t.goto(-135,-50)
t.pendown()
t.circle(50)
t.penup()
t.color("green")
t.goto(-5,-50)
t.pendown()
t.circle(50)
turtle.exitonclick() #그래픽창 안 닫히게 하기 위해서 마지막에 추가(클릭시 창 닫힘)